// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Entities;

namespace Repository.Migrations
{
    [DbContext(typeof(ManualDeploymentContext))]
    [Migration("20240115173604__p6")]
    partial class _p6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Entities.Applicative", b =>
                {
                    b.Property<int>("ApplicativeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameApplicative")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicativeID");

                    b.ToTable("Applicatives");
                });

            modelBuilder.Entity("Repository.Entities.Blueprint", b =>
                {
                    b.Property<int>("BlueprintID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Version")
                        .HasColumnType("real");

                    b.HasKey("BlueprintID");

                    b.HasIndex("ChangeID");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("Repository.Entities.Change", b =>
                {
                    b.Property<int>("ChangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeApplicativeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<DateTime>("applicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("changeDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("changeType")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("changerNumber")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("checkList")
                        .HasColumnType("bit");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("deploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("modificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("requestType")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChangeID");

                    b.HasIndex("ChangeApplicativeID");

                    b.HasIndex("UserID");

                    b.ToTable("Changes");
                });

            modelBuilder.Entity("Repository.Entities.ChangeApplicative", b =>
                {
                    b.Property<int>("ChangeApplicativeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicativeID")
                        .HasColumnType("int");

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<int>("EnvironmentID")
                        .HasColumnType("int");

                    b.HasKey("ChangeApplicativeID");

                    b.HasIndex("ApplicativeID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("EnvironmentID");

                    b.ToTable("ChangeAplicatives");
                });

            modelBuilder.Entity("Repository.Entities.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<int?>("ChangesChangeID")
                        .HasColumnType("int");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.HasKey("ContactID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("ChangesChangeID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Repository.Entities.Environment", b =>
                {
                    b.Property<int>("EnvironmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameEnvironment")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnvironmentID");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("Repository.Entities.EnvironmentApplicative", b =>
                {
                    b.Property<int>("EnvironmentApplicativeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicativeID")
                        .HasColumnType("int");

                    b.Property<int>("EnvironmentID")
                        .HasColumnType("int");

                    b.Property<int>("ServerID")
                        .HasColumnType("int");

                    b.HasKey("EnvironmentApplicativeID");

                    b.HasIndex("ApplicativeID");

                    b.HasIndex("EnvironmentID");

                    b.HasIndex("ServerID");

                    b.ToTable("EnvironmentApplicatives");
                });

            modelBuilder.Entity("Repository.Entities.FunctionalUser", b =>
                {
                    b.Property<int>("FunctionalUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<int?>("ChangesChangeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FunctionalUserID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("ChangesChangeID");

                    b.HasIndex("UserID");

                    b.ToTable("FunctionalUsers");
                });

            modelBuilder.Entity("Repository.Entities.Plan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<int?>("ChangesChangeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("int");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollbackPlanID")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("supplierArea")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("ChangesChangeID");

                    b.HasIndex("RollbackPlanID");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Repository.Entities.Postimplantacion", b =>
                {
                    b.Property<int>("PostimplantacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<int?>("ChangesChangeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PostimplantacionID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("ChangesChangeID");

                    b.HasIndex("UserID");

                    b.ToTable("Postimplantacions");
                });

            modelBuilder.Entity("Repository.Entities.Prerrequisitos", b =>
                {
                    b.Property<int>("PrerrequisitoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<int?>("ChangesChangeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionTime")
                        .HasColumnType("int");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollbackPreID")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SupplierArea")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PrerrequisitoID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("ChangesChangeID");

                    b.HasIndex("RollbackPreID");

                    b.HasIndex("UserID");

                    b.ToTable("Prerrequisitos");
                });

            modelBuilder.Entity("Repository.Entities.Profile", b =>
                {
                    b.Property<int>("ProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("TypeofProfile")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileID");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Repository.Entities.ProfileUser", b =>
                {
                    b.Property<int>("ProfileUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProfileID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProfileUserID");

                    b.HasIndex("ProfileID");

                    b.HasIndex("UserID");

                    b.ToTable("ProfileUsers");
                });

            modelBuilder.Entity("Repository.Entities.ResponsibleArea", b =>
                {
                    b.Property<int>("ResponsibleAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResponsibleAreaId");

                    b.ToTable("ResponsibleAreas");
                });

            modelBuilder.Entity("Repository.Entities.Result", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Approved")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<int?>("ChangesChangeID")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reprobate")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResultID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("ChangesChangeID");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Repository.Entities.RollbackPlan", b =>
                {
                    b.Property<int>("RollbackPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("RollbackPlanID");

                    b.HasIndex("PlanID");

                    b.ToTable("RollbackPlans");
                });

            modelBuilder.Entity("Repository.Entities.RollbackPre", b =>
                {
                    b.Property<int>("RollbackPreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrerrequisitoID")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("RollbackPreID");

                    b.HasIndex("PrerrequisitoID")
                        .IsUnique();

                    b.ToTable("Rollbackpres");
                });

            modelBuilder.Entity("Repository.Entities.Server", b =>
                {
                    b.Property<int>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameServer")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerID");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Repository.Entities.Signature", b =>
                {
                    b.Property<int>("SignatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<int?>("ChangesChangeID")
                        .HasColumnType("int");

                    b.Property<string>("EmailName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observatins")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainedUserID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SignatureID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("ChangesChangeID");

                    b.HasIndex("UserID");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("Repository.Entities.Training", b =>
                {
                    b.Property<int>("TrainingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<int?>("ChangesChangeID")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataTraining")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issues")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TrainingID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("ChangesChangeID");

                    b.HasIndex("UserID");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetworkUser")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Repository.Entities.UserChange", b =>
                {
                    b.Property<int>("UserChangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeID")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserChangeID");

                    b.HasIndex("ChangeID");

                    b.HasIndex("UserID");

                    b.ToTable("UserChanges");
                });

            modelBuilder.Entity("Repository.Entities.Blueprint", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany("Blueprints")
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Change");
                });

            modelBuilder.Entity("Repository.Entities.Change", b =>
                {
                    b.HasOne("Repository.Entities.ChangeApplicative", "ChangeApplicative")
                        .WithMany()
                        .HasForeignKey("ChangeApplicativeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangeApplicative");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.ChangeApplicative", b =>
                {
                    b.HasOne("Repository.Entities.Applicative", "Applicative")
                        .WithMany()
                        .HasForeignKey("ApplicativeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicative");

                    b.Navigation("Change");

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Repository.Entities.Contact", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Change", "Changes")
                        .WithMany("Contacts")
                        .HasForeignKey("ChangesChangeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Change");

                    b.Navigation("Changes");
                });

            modelBuilder.Entity("Repository.Entities.EnvironmentApplicative", b =>
                {
                    b.HasOne("Repository.Entities.Applicative", "Applicative")
                        .WithMany()
                        .HasForeignKey("ApplicativeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicative");

                    b.Navigation("Environment");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Repository.Entities.FunctionalUser", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Change", "Changes")
                        .WithMany("FunctionalUsers")
                        .HasForeignKey("ChangesChangeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Change");

                    b.Navigation("Changes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Plan", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Change", "Changes")
                        .WithMany("Plans")
                        .HasForeignKey("ChangesChangeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.RollbackPlan", "RollbackPlan")
                        .WithMany()
                        .HasForeignKey("RollbackPlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Change");

                    b.Navigation("Changes");

                    b.Navigation("RollbackPlan");
                });

            modelBuilder.Entity("Repository.Entities.Postimplantacion", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Change", "Changes")
                        .WithMany("Postimplantacions")
                        .HasForeignKey("ChangesChangeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Change");

                    b.Navigation("Changes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Prerrequisitos", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Change", "Changes")
                        .WithMany("Prerrequisitos")
                        .HasForeignKey("ChangesChangeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.RollbackPre", "RollbackPre")
                        .WithMany()
                        .HasForeignKey("RollbackPreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Change");

                    b.Navigation("Changes");

                    b.Navigation("RollbackPre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.ProfileUser", b =>
                {
                    b.HasOne("Repository.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Result", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Change", "Changes")
                        .WithMany("Results")
                        .HasForeignKey("ChangesChangeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Change");

                    b.Navigation("Changes");
                });

            modelBuilder.Entity("Repository.Entities.RollbackPlan", b =>
                {
                    b.HasOne("Repository.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Repository.Entities.RollbackPre", b =>
                {
                    b.HasOne("Repository.Entities.Prerrequisitos", "Prerrequisitos")
                        .WithOne()
                        .HasForeignKey("Repository.Entities.RollbackPre", "PrerrequisitoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prerrequisitos");
                });

            modelBuilder.Entity("Repository.Entities.Signature", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Change", "Changes")
                        .WithMany("Signatures")
                        .HasForeignKey("ChangesChangeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Change");

                    b.Navigation("Changes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Training", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Change", "Changes")
                        .WithMany("Trainings")
                        .HasForeignKey("ChangesChangeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Change");

                    b.Navigation("Changes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.UserChange", b =>
                {
                    b.HasOne("Repository.Entities.Change", "Change")
                        .WithMany()
                        .HasForeignKey("ChangeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Change");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Change", b =>
                {
                    b.Navigation("Blueprints");

                    b.Navigation("Contacts");

                    b.Navigation("FunctionalUsers");

                    b.Navigation("Plans");

                    b.Navigation("Postimplantacions");

                    b.Navigation("Prerrequisitos");

                    b.Navigation("Results");

                    b.Navigation("Signatures");

                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
